# Generated by Django 4.1 on 2022-08-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_pricing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
